version: "3.8"
services:
  web:
#    build: .
    image: url_shortener
    ports:
    - 5000:5000
    depends_on:
      - redis
    restart: always
    environment:
      REDIS_LOCATION: "redis://redis:6379/1"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      FLASK_PORT: 5000
    volumes:
    - .:/app
  redis:
    image: redis:5.0-alpine
    restart: on-failure
    ports:
    - 6379:6379
    command: redis-server --appendonly yes
    volumes:
    - redis_data:/data

volumes:
  redis_data: